TempProject/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TempProject.Models
{
    public class Customer : Person
    {
    }
}

TempProject/Models/EDataContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using TempProject.Models;

namespace TempProject.Models
{
    public class EDataContext : DbContext
    {
        public EDataContext() : base("SistemaDatabase") { }

        public DbSet<Person> Person { get; set; }
    }
}

TempProject/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TempProject.Models
{
    public class Employee : Person 
    { 
    }
}

TempProject/Models/FormData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;

namespace TempProject.Models
{
    public class FormData
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "A Code is required")]
        public int Code { get; set; }

        [Required(ErrorMessage = "A Name is required")]
        public string Name { get; set; }

        [EnumDataType(typeof(GenderTypes), ErrorMessage = "Invalid Gender")]
        public GenderTypes Gender { get; set; }

        [EnumDataType(typeof(PersonTypes), ErrorMessage = "Invalid Person")]
        public PersonTypes PersonType { get; set; }

        public string ToJSON()
        {
            return new JavaScriptSerializer().Serialize(this);
        }
    }

    public enum GenderTypes { Male, Female };
    public enum PersonTypes { Customer, Employee };
}

TempProject/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;

namespace TempProject.Models
{
    public class Person
    {
        public int? Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public GenderTypes Gender { get; set; }
    }
}

TempProject/Models/PersonDAO.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TempProject.Models
{
    public class PersonDAO
    {
        private EDataContext context;
        
        public PersonDAO(EDataContext context)
        {
            this.context = context;
        }

        public List<Person> GetAll()
        {
            return this.context.Person.ToList();
        }

        public void Add(Person person)
        {
            this.context.Person.Add(person);
            this.context.SaveChanges();    
        }

        public void Update(Person person)
        {
            Person entity = this.context.Person.Find(person.Id);
            if (entity == null)
                return;
            
            this.context.Entry(entity).CurrentValues.SetValues(person);
            context.SaveChanges();
        }

        public void Remove(int id)
        {    
            Person person = context.Person.Find(id);
            context.Person.Remove(person);
            context.SaveChanges();   
        }
    }
}

TempProject/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TempProject.Helpers;
using TempProject.Models;

namespace TempProject.Controllers
{
    public class PersonController : Controller
    {
        private PersonDAO personDAO;
        public PersonController(PersonDAO personDAO)
        {
            this.personDAO = personDAO;
        }

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.People = ParserHelper.GetFormDataList(personDAO.GetAll());
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormData formData)
        {
            if (ModelState.IsValid)
            {
                this.personDAO.Add(ParserHelper.GetPerson(formData));
                ViewBag.SuccessMessage = "Person added successfully!";
                ModelState.Clear();
            }

            return this.Index();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(FormData formData)
        {
            if (ModelState.IsValid)
            {
                this.personDAO.Update(ParserHelper.GetPerson(formData));
                ViewBag.SuccessMessage = "Person updated successfully!";
            }

            return this.Index();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(FormData formData)
        {
            if (ModelState.IsValid)
            {
                this.personDAO.Remove((int)ParserHelper.GetPerson(formData).Id);
                ViewBag.SuccessMessage = "Person removed successfully!";
                ModelState.Clear();
            }

            return this.Index();
        }
	}
}

TempProject/Views/Person/Index.cshtml
@using TempProject.Helpers;
@using TempProject.Models;
@model TempProject.Models.FormData

@{
    ViewBag.Title = "Index";
    List<FormData> people = (List<FormData>)ViewBag.People;
}

<h2>Index! Teste!</h2>

<form id="personForm" method="post">

    @if (ViewBag.SuccessMessage != null){
        <p class="alert alert-success">@ViewBag.SuccessMessage</p>
    }
    else if (ViewBag.ErrorMessage != null){ 
        <p class="alert alert-danger">@ViewBag.ErrorMessage</p>
    }
    
    @Html.AntiForgeryToken()
    
    @Html.HiddenFor(f => f.Id, new { @id="personId"})
    
    <div class="row">

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(f => f.Code)
                @Html.TextBoxFor(f => f.Code, new { @class= "form-control"})
                @Html.ValidationMessageFor(f => f.Code)
            </div>
    
            <div class="form-group">
                @Html.LabelFor(f => f.Name)
                @Html.TextBoxFor(f => f.Name, new { @class= "form-control"})
                @Html.ValidationMessageFor(f => f.Name)
            </div>
    
            <div class="form-group">
                @Html.LabelFor(f => f.Gender)
                @Html.DropDownListFor(f => f.Gender, MyHtmlHelper.GetEnumSelectList<GenderTypes>(), "Select Gender", new { @class= "form-control"})
                @Html.ValidationMessageFor(f => f.Gender)
            </div>

        </div>

        <div class="col-md-6">

            @Html.LabelFor(f => f.PersonType)
            <div class="radio">
                @Html.RadioButtonFor(f => f.PersonType, PersonTypes.Customer, new {@checked=true })
                @Html.Label(PersonTypes.Customer.ToString())
            </div>
            <div class="radio">
                @Html.RadioButtonFor(f => f.PersonType, PersonTypes.Employee)
                @Html.Label(PersonTypes.Employee.ToString())
            </div>
            @Html.ValidationMessageFor(f => f.PersonType)
            
        </div>

    </div>

    <div class="row">
        <div class="col-md-12" style="margin:15px 0;">
            <button type="button" class="btn btn-default" onclick="ResetForm()">New/Cancel</button>
            <button type="button" class="btn btn-primary" onclick="Save()">Save</button>
            <button type="button" class="btn btn-danger" onclick="Delete()">Delete</button>
        </div>
    </div>

</form>

@if (people != null && people.Count > 0)
{
    <table style="margin-top:20px" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Type</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            @foreach (FormData person in people)
            {
                <tr onclick="FillForm('@person.ToJSON()', '@person.Gender', '@person.PersonType')">
                    <td>@person.Id</td>
                    <td>@person.Code</td>
                    <td>@person.Name</td>
                    <td>@person.Gender</td>
                    <td>@person.PersonType</td>
                    <td><span class="glyphicon glyphicon-pencil text-primary"></span></td>
                </tr>
            }
        </tbody>
    </table>
}

@section Scripts{
    
    <script type="text/javascript">

        var validator = $("#personForm").validate({
            rules: {
                Code: {
                    required: true,
                },
                Name: {
                    required: true,
                },
                Gender: {
                    required: true
                }
            }
        });

        function ResetForm(){
            $('#personId').val("");
            $('#personForm').find("input[type=text], select").val("");
        }

        function Save() {
            var id = parseInt($('#personId').val());
            if (id > 0) {
                return Update();
            }
            Create();
        }

        function Update() {
            $('#personForm').attr('action', '@Url.Action("Update")').submit();
        }

        function Create() {
            $('#personForm').attr('action', '@Url.Action("Create")').submit();
        }

        function Delete() {
            $('#personForm').attr('action', '@Url.Action("Delete")').submit();
        }
 
        function FillForm(person, gender, personType) {

            var personObj = JSON.parse(person);
            
            $('#personId').val(personObj.Id);
            $('#Code').val(personObj.Code);
            $('#Name').val(personObj.Name);
            $('#Gender').val(gender);
            $('input[name="PersonType"][value="' + personType + '"]').prop('checked', true);
        }

    </script>
}

TempProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Styles/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Styles/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Content/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Person", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET MVC 5 - CRUD Example</p>
        </footer>
    </div>

    <script src="~/Content/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Content/Scripts/jquery.validate.min.js"></script>
    <script src="~/Content/Scripts/bootstrap.min.js"></script>

    @RenderSection("Scripts", false)

</body>
</html>